### ISSUE TITLE
Stream pages overlap

### ISSUE THREAD

**Issue by Lancey6** [kylewm/redwind#52]
There's an overlap between pages of posts, where the last posts on one page also appear as the first posts on the next page. This doesn't happen all the time, and the number of posts that overlap between pages varies.

**Comment by kylewm** [comment]
I have noticed this too and haven't figured out what causes it! Best guess is a timezone mismatch, where the pages are rendering with -0700 but the actual DB query is using +0000, so we get overlaps for posts after about 5pm.

**Comment by Lancey6** [comment]
Oh, well then clearly step 1 is getting the query and rendering timezones to match up

**Comment by kylewm** [comment]
This also causes an issue with events, where it tries to show all events that haven't ended yet on the home page...

It looks like I'm an idiot and `start_utc` and `end_utc` are not actually stored in UTC.

**Comment by kylewm** [comment]
fixed in 36a916da2e35d08ab91ec90406e446fba9e6801f

**Comment by kylewm** [comment]
Nope, over-corrected.
