### ISSUE TITLE
Images are not included in drafts properly

### ISSUE THREAD

**Issue by Lancey6** [kylewm/redwind#55]
Uploading an image with a post and saving that post as a draft inserts the markdown into the content, but does not include the image in the draft. Publishing the draft does not include the image either.

**Comment by Lancey6** [comment]
Disregard this - not sure what's going on. Image uploads work randomly for me. I'll see if it's something on my end and open a new issue if it's a problem

**Comment by kylewm** [comment]
@Lancey6 this is likely related to #25 when publishing/unpublishing a draft. On top of that, every time you save or re-save a draft its permalink changes, which I'm guessing means we lose the (file system) path to the uploaded image and can't find it.

I will have to give some thought to how to fix this...

**Comment by kylewm** [comment]
All right, tell me if this sounds reasonable. Right now images upload to  `_data/[post-path]/files/[image_name.jpg]`. This is an artifact of when Red Wind stored everything in flat files. Now that post data is stored in the DB, there's nothing connecting posts with their images.

Instead when you upload an image, give it a unique hash, and upload it to 

`_data/hash[0]/hash[:1]/hash`

and save a reference to it as part of the post 

```
{
  "attachments": [{
    "uid": hash,
    "name": photo.jpg,
    "type": "image/jpeg"
   }]
}
```

Then the images are connected to the post forever, regardless if its path changes.

I think is more or less what Known does. I think it would work better, but it's more complex, more data to store/relationships to maintain.

**Comment by Lancey6** [comment]
This was resolved for drafts, but now images are not uploading properly for photo posts. Not sure if this is an issue on my side only or if I'm not doing something I have to.

**Comment by kylewm** [comment]
Hmm, it's working for me; what are the symptoms?

**Comment by Lancey6** [comment]
Nevermind, this was an issue with my theme. I've resolved it
