### ISSUE TITLE
Tweet text is not parsed correctly

### ISSUE THREAD

**Issue by Lancey6** [kylewm/redwind#66]
Contexts don't get the same treatment as the content of a post, meaning that @-names and links aren't parsed.

**Comment by kylewm** [comment]
is this problem specific to replying to Twitter contexts, or are you wanting it in the general case?

**Comment by Lancey6** [comment]
I'm thinking we'd need it in the general case. It's weird that our posts would have links and references parsed and linked properly, but contexts would just be plaintext.

For example, if I replied to someone's post containing a link, a follower of my site would have to then go to the original post in order to click the link.

**Comment by kylewm** [comment]
well that at least shouldn't be true. HTML in the original is preserved (unless the post you're replying to is very long, then RW takes the plaintext version and truncates it), so as long as those things were linked in the original, they should be linked in the context.

**Comment by Lancey6** [comment]
The issue is that tweets do not preserve HTML, they use the tweet's text property.

**Comment by kylewm** [comment]
I think I'd like to start proxying through https://granary-demo.appspot.com to generate mf2 representations for instagram and twitter (that's what I did in Woodwind). That links up everything like it's supposed to.

**Comment by kylewm** [comment]
(decided for now, much easier to just link them ourself)
