### ISSUE TITLE
OpenGraph not parsed correctly from some sites

### ISSUE THREAD

**Issue by Lancey6** [kylewm/redwind#74]
Specifically, this page: https://gigaom.com/2015/08/24/hypertext-50/

The og tags are there but they're not being read.

**Comment by Lancey6** [comment]
Looks like they forbid access by bots or something. Trying to access the page via `requests.get` gets a 403 error.

**Comment by kylewm** [comment]
In woodwind, I've set the user agent to `Woodwind (https://github.com/kylewm/woodwind)` since lots of sites (esp wordpress) block access from unmodified user agents. We should do something similar in RW.
