### ISSUE TITLE
atom feed missing pictures

### ISSUE THREAD

**Issue by snarfed** [kylewm/redwind#76]
low priority, obviously! :P example:
<img width="1280" alt="screen shot 2015-09-21 at 10 30 07 am" src="https://cloud.githubusercontent.com/assets/778068/9999559/e71bf510-604b-11e5-9170-c3e30765700c.png">

**Comment by kylewm** [comment]
Thanks for the heads up! (Sheesh, it would have been broken for months and I had no idea) 

Fixed in https://github.com/kylewm/redwind/commit/104a73a23779e4b6076083dd6fd75396ac3e39eb

**Comment by snarfed** [comment]
thanks!

**Comment by snarfed** [comment]
just fyi, looks like this regressed. e.g. here's the top item in your atom feed right now. (low priority, obviously!)

```xml
    <content type="html" xml:base="https://kylewm.com" xml:space="preserve">

        &lt;p&gt;What does it mean when Firefox does this? Seems to have a particular issue with &lt;a class=&#34;auto-link&#34; href=&#34;http://Brid.gy&#34;&gt;Brid.gy&lt;/a&gt; right now&lt;/p&gt;

            &lt;a href="https://kylewm.com/2016/01/what-does-it-mean-when-firefox-does-this-seems-to/files/firefox-GET-failure.png">
              &lt;img src="/imageproxy?url=https%3A%2F%2Fkylewm.com%2F2016%2F01%2Fwhat-does-it-mean-when-firefox-does-this-seems-to%2Ffiles%2Ffirefox-GET-failure.png&amp;w=600&amp;h=600&amp;mode=clip&amp;sig=cf5350912e0a47844242fe1c6a34aab4f2d2fafa" />
            &lt;/a>

    </content>
```

**Comment by kylewm** [comment]
I accidentally posted that note without an image the first time. Is it possible PuSH beat me to fixing it?

**Comment by snarfed** [comment]
looks like all of the `<img>` tags in your atom have relative `/imageproxy...` urls like in the example above.

**Comment by snarfed** [comment]
oh! it showed up in my reader again just now with the image. maybe due to a new id. so you're probably right, i saw the original imageless post first.

i guess atom parsing and rendering is smarter about relative urls than i guessed. :P

**Comment by kylewm** [comment]
surprisingly little info about it online, but I think `xml:base` is supposed to tell it where to base relative urls from. thanks for the heads up!
