### ISSUE TITLE
atom feed: render repost originals

### ISSUE THREAD

**Issue by snarfed** [kylewm/redwind#80]
...pretty please? :P

example: 
<img width="457" alt="screen shot 2015-10-06 at 4 10 04 pm" src="https://cloud.githubusercontent.com/assets/778068/10325245/8e8222b2-6c44-11e5-9bb7-779e5de0353c.png">

**Comment by kylewm** [comment]
How the tables have turned!

**Comment by snarfed** [comment]
lol touché, well played

**Comment by kylewm** [comment]
Thanks for the heads up!

**Comment by snarfed** [comment]
:pray:
