### ISSUE TITLE
Hashsigns (#) at the start of a note are parsed as a header

### ISSUE THREAD

**Issue by Lancey6** [kylewm/redwind#81]
Not sure if intended, but putting a hashtag at the start of a note parses it as a header in markdown rather than a tag and removes the hash sign in the post and when it's syndicated to Twitter (and other silos).

**Comment by kylewm** [comment]
hmm yeah this annoys me too, particularly for instagram/OwnYourGram posts. Probably good to just special case it to \ escape the # if it's the first character before running through Markdown.

Thanks for the bump.

**Comment by kylewm** [comment]
That's a little bit of a blunt fix, but it should cover all my use cases... Let me know if it doesn't for you.
