### ISSUE TITLE
de-duping isn't working for rsvps?

### ISSUE THREAD

**Issue by snarfed** [kylewm/redwind#82]
looks like maybe not: https://kylewm.com/2015/11/sf-homebrew-website-club-1

low priority, obviously!

**Comment by kylewm** [comment]
It looks like there are two different posts?
https://snarfed.org/2015-11-05_kyle-mahan-sf-homebrew-website-club
https://snarfed.org/2015-11-05_homebrew-website-club-anniversary

**Comment by snarfed** [comment]
ah you're right, i changed the slug for no good reason. never mind!
